/**
 * Primus OS Business Edition - Governance Event Service
 *
 * Records all governance events for compliance audit trail.
 * Every significant action in the system generates an event.
 */

import { GovernanceEvent, GovernanceEntityType } from '../../types';
import { GovernanceRepository } from '../../infra/repositories/GovernanceRepository';

export interface RecordEventParams {
  firmId: string;
  entityType: GovernanceEntityType;
  entityId: string;
  eventType: string;
  performedBy: string; // user ID or "SYSTEM"
  payload?: Record<string, any>;
}

export class GovernanceEventService {
  constructor(private repository: GovernanceRepository) {}

  /**
   * Record a governance event
   */
  async record(params: RecordEventParams): Promise<GovernanceEvent> {
    const event: GovernanceEvent = {
      id: '', // Will be generated by DB
      firmId: params.firmId,
      entityType: params.entityType,
      entityId: params.entityId,
      eventType: params.eventType,
      performedBy: params.performedBy,
      payload: params.payload || {},
      occurredAt: new Date(),
    };

    const savedEvent = await this.repository.insertEvent(event);

    console.log('[GOVERNANCE EVENT]', {
      type: savedEvent.eventType,
      entity: `${savedEvent.entityType}:${savedEvent.entityId}`,
      actor: savedEvent.performedBy,
    });

    return savedEvent;
  }

  /**
   * Query events for an entity
   */
  async getEventsForEntity(
    entityType: GovernanceEntityType,
    entityId: string
  ): Promise<GovernanceEvent[]> {
    return this.repository.findEventsByEntity(entityType, entityId);
  }

  /**
   * Query events for a firm (audit trail)
   */
  async getEventsForFirm(
    firmId: string,
    options?: {
      limit?: number;
    }
  ): Promise<GovernanceEvent[]> {
    return this.repository.findEventsByFirm(firmId, options?.limit);
  }

  /**
   * Get recent activity summary for dashboard
   */
  async getRecentActivity(firmId: string, limit = 50): Promise<GovernanceEvent[]> {
    return this.getEventsForFirm(firmId, { limit });
  }
}
